### PR TITLE
healpy build will fail on OS X

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by timj** [comment]
Can the commit message be fixed please?

**Comment by jhoblitt** [comment]
That was odd... should be fixed.

**Comment by timj** [comment]
I guess this patch is fine. Seems harmless.

**Comment by jhoblitt** [comment]
I will merge it once https://ci.lsst.codes/job/stack-os-matrix/8530/ finishes

**Comment by jhoblitt** [comment]
https://ci.lsst.codes/job/stack-os-matrix/8530/ passed

**Pull request merged**
